version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./views:/root/views
      - ./conf:/root/conf
    environment:
      - ENV=development
      - BUILDVCS=false  # Disable VCS stamping
